### ISSUE TITLE
Easily closable window needed

### ISSUE THREAD

**Issue by extrowerk** [emctague/abstrakt#1]
Thanks for the nice program, it is 100% that what i've searched for.

It would be nice, if one could close the main window with esc or with the standard close shortcuts.
I use Abstrakt with a shortcut, so if i met with something, i just press Meta-A, Abstrakt opens, i type my question, get the answer, and then i would just close fast and easily.
Currently Abstrakt needs to be closed with mouse as it doesn't respects the standard closing shortcuts.

If you can add this feature, that would be greatly appreciated.

**Comment by extrowerk** [comment]
Btw, the current Haiku recipe resides here: https://github.com/haikuports/haikuports/pull/2551

**Comment by emctague** [comment]
Hi, sorry for taking so long to respond, I've been ignoring my email lately. I'm happy you like it, I'm on a new PC and don't have a local development setup but I'll try to get a shortcut like this, as well as your other request, soon!

**Comment by emctague** [comment]
**Update:** I have added this feature! You can now use `Esc` and `Ctrl-Q` to quit the app instantly. If you could test it out and confirm it works for you, I would appreciate it.

**Comment by extrowerk** [comment]
It works with Esc, thanks!
On Haiku the standardized "close" shortcut is Alt-W, sadly that doesn't work, while it works just fine with other Qt5 programs.

**Comment by emctague** [comment]
Hi, I forgot Qt has a built-in way to use the standard platform shortcuts.
I'll add that as an option, too, thanks.

>
