### ISSUE TITLE
Window opens in left top corner

### ISSUE THREAD

**Issue by extrowerk** [emctague/abstrakt#2]
It should open in the middle of the screen.

**Comment by extrowerk** [comment]
Or at least it should remember, where the user positioned it last time.

**Comment by emctague** [comment]
Hi, I've added this feature! Please let me know if it works!

**Comment by extrowerk** [comment]
Lemme test it later! Thanks mate, great job!

**Comment by extrowerk** [comment]
It works great, thank you mate!
